apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: mlflow-serving
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/mlflow-env.yaml
      - k8s/mlflow-serving-conf.yaml
      - k8s/mlflow-serving.yaml
