apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: mlflow-serving
      context: .
      custom:
        buildCommand: ./build.sh
deploy:
  kubectl:
    manifests:
      - k8s/mlflow-env.yaml
      - k8s/mlflow-serving-conf.yaml
      - k8s/mlflow-serving.yaml
profiles:
  - name: staroid
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: ./k8s/ske.yaml
