apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-serving
  template:
    metadata:
      labels:
        app: mlflow-serving
        pod.staroid.com/spot: "true"
    spec:
      containers:
      - name: mlflow-serving
        image: mlflow-serving
        command: 
        - "ttyd"
        - "-R"
        - "bash"
        - "-c"
        - >-
          mkdir -p ~/.ssh && chmod 700 ~/.ssh &&
          echo -n "$(echo $MLFLOW_TRACKING_URI | sed 's/.*\(mlflow[^:]*\).*/\1/g') " >> ~/.ssh/known_hosts &&
          echo $MLFLOW_ARTIFACT_STORE_RSA_PUB | base64 --decode >> ~/.ssh/known_hosts &&
          echo $MLFLOW_ARTIFACT_STORE_RSA_PRI | base64 --decode >> ~/.ssh/id_rsa &&
          chmod 600 ~/.ssh/* &&
          mlflow models serve
          -m "$MODEL_URI"
          -p 5001
          -h 0.0.0.0
          --install-mlflow ||
          echo "done"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: mlflow-serving-conf
        - configMapRef:
            name: mlflow-env
---
kind: Service
apiVersion: v1
metadata:
  name: mlflow-serving
spec:
  ports:
  - name: console
    port: 7681
  - name: mlflow-serving
    port: 5001
  selector:
    app: mlflow-serving
